apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: csi-s3
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
  - wrangler.cattle.io/on-helm-chart-remove
spec:
  # https://github.com/yandex-cloud/k8s-csi-s3
  repo: https://yandex-cloud.github.io/k8s-csi-s3/charts
  chart: csi-s3
  version: v0.43.0
  targetNamespace: csi-s3
  createNamespace: true
  valuesContent: |-
    secret:
      create: false