apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels:
    app: landing
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      volumes:
      - name: var-www
        configMap:
          name: var-www
      containers:
      - name: landing
        # https://hub.docker.com/_/nginx
        image: nginx:1.29.3
        volumeMounts:
        - name: var-www
          mountPath: /usr/share/nginx/html
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: landing
spec:
  selector:
    app: landing
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-oauth2-proxy-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - "landing.home.cambridge.me"
    secretName: landing-home-cambridge-me-tls
  rules:
  - host: landing.home.cambridge.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing
            port:
              name: http