apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsmr-metrics-proxy
  labels:
    app.kubernetes.io/name: dsmr-metrics-proxy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dsmr-metrics-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dsmr-metrics-proxy
    spec:
      containers:
      - name: caddy
        image: caddy:2.10.2-alpine
        command:
        - caddy
        args:
        - reverse-proxy
        - --from
        - :8080
        - --to
        - dsmr.cambridge.me:80
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dsmr
  labels:
    app.kubernetes.io/name: dsmr
spec:
  selector:
    app.kubernetes.io/name: dsmr-metrics-proxy
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dsmr
  labels:
    prometheus: energy
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dsmr
  endpoints:
  - interval: 5m
    port: http
    path: /metrics
