apiVersion: v1
kind: ConfigMap
metadata:
  name: energy-prometheus-datasource
  labels:
    grafana_datasource: "1"
data:
  energy-prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Energy Prometheus
      uid: energy-prometheus
      type: prometheus
      access: proxy
      url: http://energy-prometheus.energy-monitoring.svc:9090
      isDefault: false
      editable: false
