apiVersion: v1
kind: ServiceAccount
metadata:
  name: energy-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: energy-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: energy-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: energy-prometheus
subjects:
- kind: ServiceAccount
  name: energy-prometheus
  namespace: energy-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: energy
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  retention: 100y
  serviceAccountName: energy-prometheus
  securityContext:
    runAsNonRoot: true
    runAsUser: 36374
    runAsGroup: 36374
    fsGroup: 36374
    fsGroupChangePolicy: OnRootMismatch
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: energy
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: glusterfs-energy-monitoring
      spec:
        storageClassName: local-path
        volumeName: glusterfs-energy-monitoring
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: energy-prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: energy
  ports:
  - name: http-web
    port: 9090
    targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: energy-prometheus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-oauth2-proxy-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: prometheus-energy.home.cambridge.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: energy-prometheus
            port:
              name: http-web
  tls:
  - hosts:
    - prometheus-energy.home.cambridge.me
    secretName: prometheus-energy-home-cambridge-me-tls
