apiVersion: v1
kind: ServiceAccount
metadata:
  name: energy-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: energy-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: energy-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: energy-prometheus
subjects:
- kind: ServiceAccount
  name: energy-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: energy
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  retention: 100y
  serviceAccountName: energy-prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: energy
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: glusterfs-energy-monitoring
      spec:
        storageClassName: local-path
        volumeName: glusterfs-energy-monitoring
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: energy-prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: energy
  ports:
  - name: http-web
    port: 9090
    targetPort: http-web
