apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  isCA: true
  commonName: ldap
  secretName: ldap-ca
  issuerRef:
    name: self-signed
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ldap-ca
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ca:
    secretName: ldap-ca
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ldap-ca
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  sources:
  - secret:
      name: ldap-ca
      key: ca.crt
  target:
    configMap:
      key: "ca.pem"
