apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  finalizers:
  - wrangler.cattle.io/on-helm-chart-remove
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.13.0
  targetNamespace: kube-system
