apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 36.3.0
  targetNamespace: kube-system
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesContent: |-
    global:
      sendAnonymousUsage: false
    deployment:
      revisionHistoryLimit: 1
    ports:
      web:
        port: 8000
        nodePort: 30000
        exposedPort: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        nodePort: 30001
        exposedPort: 443
    ingressClass:
      enabled: false
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
    gateway:
      listeners:
        web:
          port: 8000
          protocol: HTTP
          namespacePolicy: All
        websecure:
          port: 8443
          protocol: HTTPS
          namespacePolicy: All
          mode: Terminate
          certificateRefs:
            - kind: Secret
              name: media-cambridge-me-tls
              group: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-cambridge-me
spec:
  secretName: media-cambridge-me-tls
  dnsNames:
    - media.cambridge.me
    - "*.media.cambridge.me"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer