apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ExternalName
  # TODO: create a dns-resolved name which points to all disknodes? or something better
  externalName: cranberry
  ports:
  - protocol: TCP
    port: 9001
