apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: dotfiles
  source:
    repoURL: https://github.com/intel/helm-charts.git
    targetRevision: intel-device-plugins-operator-0.35.0
    path: charts/device-plugin-operator/crds
    directory:
      include: deviceplugin.intel.com_gpudeviceplugins.yaml
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: intel-gpu
    server: https://kubernetes.default.svc
  project: dotfiles
  source:
    repoURL: git@github.com:rcambrj/dotfiles
    targetRevision: HEAD
    path: kubernetes/intel-gpu/plugin
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
